### ISSUE TITLE
Please remove the secret related to our organization.

### ISSUE THREAD

**Issue by adithyasaahas** [digcre/terraform-lab#1]
The following secret was found in commit `59037376fdd549ee4daf41506e7cea0bab0d6525` in file `terraform/code/sandbox1/vars.tfvars`:

```
9652d7c2-1ccf-4940-8151-4a92bd474ed0
```

https://github.com/digcre/terraform-lab/blob/59037376fdd549ee4daf41506e7cea0bab0d6525/terraform/code/sandbox1/vars.tfvars#L4

Please remove/delete it ASAP.

**Comment by digcre** [comment]
fixed
